# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee5a31ac0326441c7a8b109a98df36dee21d6f7188e01e31b94cdc26eebd1901e7d6bb1a818bddb6450471936f010165dd8623bda7ad50bc6089b83593326865

test:
  secret_key_base: 756ae50cea949208f7582623ce30a01d3c42019cb5565b52af857cac0936f9f27f049e3800c42a5e585a967db008a1f9641f1a724203333c0db04536633b936b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
